# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:

  ca0.org2.example.com: 
    container_name: ca0.org2.lychee.com
    image: hyperledger/fabric-ca 
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server 
      - FABRIC_CA_SERVER_CA_NAME=ca0-org2 
      - FABRIC_CA_SERVER_TLS_ENABLED=false 
    # docker启动后启动一个ca server ，注意修改根证书和admin密码
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.lychee.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7d6dcec864394c12bd695302ba027eabe0055b61999c92817dc990e31a487f1b_sk -b admin:adminpw -d' 
    volumes: 
      - ./crypto-config/peerOrganizations/org2.lychee.com/ca/:/etc/hyperledger/fabric-ca-server-config 
    ports: 
      - "7054:7054" 